# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1719e3a3671ac18d64d40e2b7426c931ed9c346150bb5ba0b19925a16b57f2ec8d6c2a3c14d8544376bfb0bcc2a9a21e30e373239e25422ffb21933e915580bd

test:
  secret_key_base: dc332f640d1f85a786807d504d601d846acca6a29ad20ed7c73bd1fa671e13f29a7c04031407b5472160d464a2810c992490b70169338c48c0c9d86eb35bd4aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
